spring:
  profiles:
    active:
      - dog
      - EN
      - dev
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrlJdbc

---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrlJdbc